# Generated by Django 3.0.2 on 2020-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sens',
            name='type',
            field=models.CharField(choices=[('Электроэнергия', 'Электроэнергия'), ('Холодная вода', 'Холодная вода'), ('Горячая вода', 'Горячая вода')], max_length=50),
        ),
    ]
